import os
from sqlalchemy import create_engine, Column, Integer, String, DateTime, Text, Boolean, Float, LargeBinary, ForeignKey, event
from sqlalchemy.orm import declarative_base, sessionmaker
import datetime

from sqlalchemy.pool import StaticPool, QueuePool

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./hyper_test.db")

if DATABASE_URL.startswith("postgresql"):
    engine = create_engine(
        DATABASE_URL,
        poolclass=QueuePool,
        pool_size=10,
        max_overflow=20,
        pool_pre_ping=True
    )
else:
    engine = create_engine(
        DATABASE_URL,
        poolclass=StaticPool,
        connect_args={"check_same_thread": False},
        pool_pre_ping=True,
        echo=False
    )

@event.listens_for(engine, "connect")
def set_sqlite_pragma(dbconn, _):
    cursor = dbconn.cursor()
    cursor.execute("PRAGMA foreign_keys=ON")
    cursor.close()

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    uid = Column(String, unique=True, index=True) # Firebase UID
    tenant_id = Column(String, index=True) # Multi-tenant isolation ID
    email = Column(String, unique=True, index=True)
    tier = Column(String, default="free") # free, pro, enterprise
    password_hash = Column(String, nullable=True) # For backend-owned auth
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class Subscription(Base):
    __tablename__ = "subscriptions"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"))
    tenant_id = Column(String, index=True)
    paypal_order_id = Column(String, unique=True)
    status = Column(String) # active, cancelled, expired
    updated_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class DocumentMetadata(Base):
    __tablename__ = "document_metadata"
    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"))
    tenant_id = Column(String, index=True)
    content_hash = Column(String)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class UsageMetric(Base):
    __tablename__ = "usage_metrics"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True)
    tenant_id = Column(String, index=True)
    metric_type = Column(String) # 'request', 'token', 'storage_bytes'
    value = Column(Integer, default=0)
    timestamp = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class QueryCluster(Base):
    """Layer 2: Canonical query clustering for answer reuse."""
    __tablename__ = "query_clusters"
    id = Column(Integer, primary_key=True, index=True)
    cluster_hash = Column(String, unique=True, index=True)
    canonical_query = Column(String)
    canonical_answer = Column(Text)
    embedding = Column(LargeBinary) # Semantic vector for O(1) clustering
    tenant_id = Column(String, index=True)
    use_count = Column(Integer, default=1)

class Workspace(Base):
    """SaaS Workspace: logical isolation for teams."""
    __tablename__ = "workspaces"
    id = Column(String, primary_key=True, index=True)
    name = Column(String)
    tenant_id = Column(String, index=True)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class Document(Base):
    """Metadata for uploaded knowledge documents."""
    __tablename__ = "documents"
    id = Column(String, primary_key=True, index=True)
    filename = Column(String)
    file_type = Column(String)
    workspace_id = Column(String, index=True)
    tenant_id = Column(String, index=True)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class PrecomputedAnswer(Base):
    """Layer 1: Answers generated by PPE before the user asks."""
    __tablename__ = "precomputed_answers"
    id = Column(Integer, primary_key=True, index=True)
    canonical_question = Column(String, index=True)
    answer = Column(Text)
    embedding = Column(LargeBinary) # Store for vector-like lookup
    confidence = Column(Float)
    cluster_id = Column(Integer, index=True)
    workspace_id = Column(String, index=True) # Multi-tenant isolation
    tenant_id = Column(String, index=True)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class ShadowAnswer(Base):
    """Layer 0: Answers predicted on-the-fly during a conversation turn."""
    __tablename__ = "shadow_answers"
    id = Column(Integer, primary_key=True, index=True)
    question = Column(String, index=True)
    answer = Column(Text)
    embedding = Column(LargeBinary)
    confidence = Column(Float)
    session_id = Column(String, index=True)
    workspace_id = Column(String, index=True) # Multi-tenant isolation
    tenant_id = Column(String, index=True)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class CompressedFragment(Base):
    """Compressed, reusable units of knowledge (fragments)."""
    __tablename__ = "compressed_fragments"
    id = Column(String, primary_key=True) # Hash-based ID
    content = Column(Text)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class CompressedKnowledge(Base):
    """Structured knowledge extracted from answers, linking fragments."""
    __tablename__ = "compressed_knowledge"
    id = Column(String, primary_key=True) # Canonical ID (intent#entity)
    concept = Column(String)
    intent = Column(String)
    key_points_json = Column(Text) # JSON list of extracted points
    fragment_ids_json = Column(Text) # JSON list of links to CompressedFragment
    tenant_id = Column(String, index=True)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class UsageLog(Base):
    """Audit trail for billing and pattern mining."""
    __tablename__ = "usage_logs"
    id = Column(Integer, primary_key=True, index=True)
    workspace_id = Column(String, index=True)
    user_id = Column(String, index=True)
    query = Column(String)
    answer = Column(Text)
    response_type = Column(String) # shadow, predictive, cache, etc.
    latency_ms = Column(Integer)
    inference_used = Column(Boolean)
    timestamp = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class PolicyDocument(Base):
    """Immutable record of an ingested enterprise policy document."""
    __tablename__ = "policy_documents"
    id = Column(Integer, primary_key=True, index=True)
    filename = Column(String, index=True)
    content_hash = Column(String, unique=True, index=True)
    authority_level = Column(String) # Global, Regional, Departmental
    department = Column(String, index=True)
    region = Column(String, index=True)
    version = Column(String)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class PolicyChunk(Base):
    """Hierarchical split of policy text clauses."""
    __tablename__ = "policy_chunks"
    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("policy_documents.id", ondelete="CASCADE"), index=True)
    section_header = Column(String)
    clause_number = Column(String, index=True)
    content = Column(Text)
    authority_level = Column(String)
    region = Column(String)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class PolicyRelationship(Base):
    """Evaluated semantic / logic links between policy chunks."""
    __tablename__ = "policy_relationships"
    id = Column(Integer, primary_key=True, index=True)
    source_chunk_id = Column(Integer, ForeignKey("policy_chunks.id", ondelete="CASCADE"), index=True)
    target_chunk_id = Column(Integer, ForeignKey("policy_chunks.id", ondelete="CASCADE"), index=True)
    relationship_type = Column(String, index=True) # CONTRADICTS, SUPERSEDES, DEPENDS_ON, etc.
    confidence = Column(Float)
    rationale = Column(Text)
    created_at = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

class AuditProvenanceLog(Base):
    """Trace logs recording the history of governance events."""
    __tablename__ = "audit_provenance_logs"
    id = Column(Integer, primary_key=True, index=True)
    action = Column(String) # 'INGEST', 'RESOLVE_CONFLICT', 'ESC_ROUTE'
    document_id = Column(Integer, index=True)
    details = Column(Text)
    actor = Column(String)
    timestamp = Column(DateTime, default=lambda: datetime.datetime.now(datetime.timezone.utc))

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
