"""
hyper_universal/types.py
========================
LEO/HYPER Ω Core Domain Types & Strict Epistemic States.

Implements Sections 4, 32, 34, 35 of the Master Specification:
- 17 Standardized Result States:
    FOUND, VERIFIED, PROVEN, GENERALIZED, TARGET_REACHED, IMPROVEMENT_FOUND,
    COUNTEREXAMPLE_FOUND, SEARCH_SATURATED, UNKNOWN, FAILURE, BARRIER,
    INVALID_COMPARISON, UNVERIFIED, SIMULATED, REFERENCE_ONLY, ESTIMATED, DERIVED.
- Provenance Types:
    MEASURED, DERIVED, ESTIMATED, SIMULATED, REFERENCE_ONLY, UNAVAILABLE.
- Mandatory Cache Regimes:
    COLD, WARM, CACHED, MEMOIZED, PRECOMPUTED, INCREMENTAL.
"""

from __future__ import annotations
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ResultState(str, Enum):
    FOUND = "FOUND"
    VERIFIED = "VERIFIED"
    PROVEN = "PROVEN"
    GENERALIZED = "GENERALIZED"
    TARGET_REACHED = "TARGET_REACHED"
    IMPROVEMENT_FOUND = "IMPROVEMENT_FOUND"
    COUNTEREXAMPLE_FOUND = "COUNTEREXAMPLE_FOUND"
    SEARCH_SATURATED = "SEARCH_SATURATED"
    UNKNOWN = "UNKNOWN"
    FAILURE = "FAILURE"
    BARRIER = "BARRIER"
    INVALID_COMPARISON = "INVALID_COMPARISON"
    UNVERIFIED = "UNVERIFIED"
    SIMULATED = "SIMULATED"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    ESTIMATED = "ESTIMATED"
    DERIVED = "DERIVED"


class MetricProvenance(str, Enum):
    MEASURED = "MEASURED"
    DERIVED = "DERIVED"
    ESTIMATED = "ESTIMATED"
    SIMULATED = "SIMULATED"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    UNAVAILABLE = "UNAVAILABLE"


class CacheRegime(str, Enum):
    COLD = "COLD"
    WARM = "WARM"
    CACHED = "CACHED"
    MEMOIZED = "MEMOIZED"
    PRECOMPUTED = "PRECOMPUTED"
    INCREMENTAL = "INCREMENTAL"


class ReferenceType(str, Enum):
    LOCAL_REFERENCE = "LOCAL_REFERENCE"
    SIMULATED_REFERENCE = "SIMULATED_REFERENCE"
    EXTERNAL_PHYSICAL_REFERENCE = "EXTERNAL_PHYSICAL_REFERENCE"
    THEORETICAL_REFERENCE = "THEORETICAL_REFERENCE"


class ClaimStatus(str, Enum):
    NOT_ESTABLISHED = "NOT_ESTABLISHED"
    PARTIALLY_ESTABLISHED = "PARTIALLY_ESTABLISHED"
    BOUNDED_ESTABLISHED = "BOUNDED_ESTABLISHED"
    GENERALIZED = "GENERALIZED"
    FORMALLY_ESTABLISHED = "FORMALLY_ESTABLISHED"
    UNKNOWN = "UNKNOWN"
