import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      ".output/**",
      ".vinxi/**",
      ".tanstack/**",
      ".vercel/**",
      ".wrangler/**",
      ".pytest_cache/**",
      ".hyper_cache/**",
      ".hyper_proxies/**",
      "e2e/**",
      "playwright-report/**",
      "test-results/**",
      "archive_engines/**",
      "ui_core/**",
      "scratch/**",
      "public/**",
      "core_ai/**",
      "supabase/**",
      "v2.0/**",
      ".venv/**",
      "venv/**",
      "node_modules/**",
      "tests/**",
      "backend/**",
      "hyper_holographic_poc/**",
      "scripts/**",
      "benchmark_workers/**",
      "benchmarks/**",
      "adapters/**",
      "alembic/**",
      "bin/**",
      "bypass/**",
      "cache/**",
      "chat_ui/**",
      "chimera/**",
      "chroma_db/**",
      "contracts/**",
      "core/**",
      "cosmic_singularity/**",
      "dashboard/**",
      "data/**",
      "deploy/**",
      "docs/**",
      "execution/**",
      "experiments/**",
      "experts/**",
      "grafana/**",
      "hyper/**",
      "hyper100/**",
      "hyper_ares/**",
      "hyper_runtime/**",
      "hyper_sdk/**",
      "hyper_x/**",
      "intel_core_ai/**",
      "k8s/**",
      "kernels/**",
      "leo/**",
      "leo_infinity_kernels/**",
      "memory/**",
      "models/**",
      "optimization/**",
      "phoenix/**",
      "physics/**",
      "pipeline/**",
      "predictors/**",
      "project_hyper/**",
      "qa_security_team/**",
      "rag/**",
      "rag_data/**",
      "render/**",
      "reports/**",
      "retrieval/**",
      "sampling/**",
      "spectral/**",
      "subsystems/**",
      "testsprite_tests/**",
      "universal_compute_router/**",
      "video/**",
      "test_falsification_runner.js",
      "autofixer.js",
      "dump.js",
      "HYPER_v6_BREAKTHROUGH/**",
      "hyper_cel/**",
      "kimi-k3/**",
      "*.timestamp-*.mjs",
      "vite.config.ts.timestamp-*.mjs",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
  eslintPluginPrettier,
);
