/**
 * ============================================================================
 * Project LEO / HYPER — High-Performance Heterogeneous Runtime
 * File: leo_speculative_engine.hpp
 *
 * Module 3: Heterogeneous Speculative Decoding & Mathematical Parity Engine
 * Target: Intel Core i5-12450H (4 P-Cores / 8 Threads + 4 E-Cores / 4 Threads)
 *
 * Architecture:
 * - Threads 8-11 (E-Cores): Asynchronous lightweight Draft Model (K=4 candidates)
 * - Threads 0-7 (P-Cores): AVX2-accelerated Batched Verification & Target Eval
 * - Rejection Sampling: Modified Leviathan-Chen rejection sampling ensuring
 *   100% MATHEMATICAL OUTPUT DISTRIBUTION EQUIVALENCE.
 * ============================================================================
 */

#ifndef LEO_SPECULATIVE_ENGINE_HPP
#define LEO_SPECULATIVE_ENGINE_HPP

#include <cstddef>
#include <cstdint>
#include <vector>
#include <string>
#include <memory>
#include <thread>
#include <future>
#include <atomic>
#include <random>
#include <cmath>
#include <algorithm>
#include <immintrin.h> // AVX2 / FMA intrinsics

#if defined(_WIN32) || defined(_WIN64)
    #include <windows.h>
    #define LEO_SPEC_EXPORT __declspec(dllexport)
#else
    #include <pthread.h>
    #include <sched.h>
    #define LEO_SPEC_EXPORT __attribute__((visibility("default")))
#endif

namespace leo {
namespace speculative {

/**
 * Speculative Candidate Chain generated by E-Cores.
 */
struct SpeculativeDraft {
    std::vector<int32_t> draft_tokens;            // Proposed token sequence of length K
    std::vector<std::vector<float>> draft_probs;   // Probability vector P_draft(x) per step
    size_t k_length = 0;                          // e.g. K = 4
};

/**
 * Verification outcome after single batched target forward pass on P-cores.
 */
struct VerificationResult {
    std::vector<int32_t> accepted_tokens;         // Tokens accepted without distribution shift
    int32_t correction_token = -1;                // Resampled token if draft was rejected, or next step
    size_t accepted_count = 0;                    // Number of speculative tokens accepted (0 to K)
    bool full_acceptance = false;
    double acceptance_rate = 0.0;
};

/**
 * CPU Core Affinity Helper for Intel Hybrid Architecture (Alder Lake / Raptor Lake).
 */
class CoreAffinityManager {
public:
    static void pinToPCores() {
        // P-Cores on i5-12450H: 4 cores / 8 Hyperthreads -> Logical CPUs 0 to 7 (Mask 0x00FF)
#if defined(_WIN32) || defined(_WIN64)
        DWORD_PTR mask = 0x00FF;
        SetThreadAffinityMask(GetCurrentThread(), mask);
#else
        cpu_set_t cpuset;
        CPU_ZERO(&cpuset);
        for (int i = 0; i < 8; ++i) CPU_SET(i, &cpuset);
        pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);
#endif
    }

    static void pinToECores() {
        // E-Cores on i5-12450H: 4 Gracemont cores -> Logical CPUs 8 to 11 (Mask 0x0F00)
#if defined(_WIN32) || defined(_WIN64)
        DWORD_PTR mask = 0x0F00;
        SetThreadAffinityMask(GetCurrentThread(), mask);
#else
        cpu_set_t cpuset;
        CPU_ZERO(&cpuset);
        for (int i = 8; i < 12; ++i) CPU_SET(i, &cpuset);
        pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);
#endif
    }
};

/**
 * High-performance AVX2 Vectorized GEMV (Matrix-Vector Multiplication).
 * Computes: y = A * x (where A is row-major [M, N], x is [N], y is [M]).
 */
inline void avx2_gemv_fp32(
    const float* __restrict A,
    const float* __restrict x,
    float* __restrict y,
    size_t M,
    size_t N)
{
    // Execute row-by-row with 256-bit FMA vector registers (8 floats per op)
    for (size_t i = 0; i < M; ++i) {
        const float* row = A + i * N;
        __m256 acc0 = _mm256_setzero_ps();
        __m256 acc1 = _mm256_setzero_ps();

        size_t j = 0;
        for (; j + 15 < N; j += 16) {
            __m256 va0 = _mm256_loadu_ps(row + j);
            __m256 vx0 = _mm256_loadu_ps(x + j);
            acc0 = _mm256_fmadd_ps(va0, vx0, acc0);

            __m256 va1 = _mm256_loadu_ps(row + j + 8);
            __m256 vx1 = _mm256_loadu_ps(x + j + 8);
            acc1 = _mm256_fmadd_ps(va1, vx1, acc1);
        }

        acc0 = _mm256_add_ps(acc0, acc1);

        // Horizontal sum of acc0
        __m128 lo = _mm256_castps256_ps128(acc0);
        __m128 hi = _mm256_extractf128_ps(acc0, 1);
        __m128 sum128 = _mm_add_ps(lo, hi);
        sum128 = _mm_hadd_ps(sum128, sum128);
        sum128 = _mm_hadd_ps(sum128, sum128);

        float sum = _mm_cvtss_f32(sum128);

        // Handle remainder elements
        for (; j < N; ++j) {
            sum += row[j] * x[j];
        }

        y[i] = sum;
    }
}

/**
 * Heterogeneous Speculative Engine.
 */
class SpeculativeEngine {
public:
    SpeculativeEngine(size_t vocab_size = 32000, size_t draft_k = 4, uint32_t seed = 42)
        : vocab_size_(vocab_size), draft_k_(draft_k), rng_(seed), dist_(0.0f, 1.0f) {}

    /**
     * Executes Exact Mathematical Rejection Sampling over Draft sequence K.
     *
     * Mathematical Guarantee:
     * Token x_i is accepted with probability:
     *   min(1.0, P_target(x_i) / P_draft(x_i))
     *
     * If rejected at index i, sample from residual:
     *   P_res(x) = max(0, P_target(x) - P_draft(x)) / norm
     *
     * This guarantees that the final output tokens follow P_target EXACTLY,
     * achieving 100% mathematical parity with zero distribution divergence.
     */
    VerificationResult verifyAndSample(
        const SpeculativeDraft& draft,
        const std::vector<std::vector<float>>& target_probs_batch)
    {
        VerificationResult res;
        res.accepted_count = 0;
        res.full_acceptance = false;

        size_t K = draft.draft_tokens.size();

        for (size_t step = 0; step < K; ++step) {
            int32_t draft_tok = draft.draft_tokens[step];
            const auto& p_draft_vec = draft.draft_probs[step];
            const auto& p_target_vec = target_probs_batch[step];

            float p_draft = (draft_tok < static_cast<int32_t>(p_draft_vec.size())) ? p_draft_vec[draft_tok] : 1e-8f;
            float p_target = (draft_tok < static_cast<int32_t>(p_target_vec.size())) ? p_target_vec[draft_tok] : 1e-8f;

            float acceptance_ratio = (p_draft > 0.0f) ? std::min(1.0f, p_target / p_draft) : 0.0f;
            float r = dist_(rng_);

            if (r < acceptance_ratio) {
                // ACCEPT DRAFT TOKEN
                res.accepted_tokens.push_back(draft_tok);
                res.accepted_count++;
            } else {
                // REJECT DRAFT TOKEN: Resample from residual distribution
                res.correction_token = sampleFromResidual(p_target_vec, p_draft_vec);
                res.acceptance_rate = static_cast<double>(res.accepted_count) / static_cast<double>(K);
                return res;
            }
        }

        // If all K tokens accepted, sample 1 additional token from target_probs_batch[K]
        if (target_probs_batch.size() > K) {
            res.correction_token = sampleDirect(target_probs_batch[K]);
        }
        res.full_acceptance = true;
        res.acceptance_rate = 1.0;
        return res;
    }

private:
    int32_t sampleFromResidual(const std::vector<float>& p_target, const std::vector<float>& p_draft) {
        std::vector<float> residual(p_target.size(), 0.0f);
        float sum = 0.0f;

        for (size_t i = 0; i < p_target.size(); ++i) {
            float d = (i < p_draft.size()) ? p_draft[i] : 0.0f;
            float diff = std::max(0.0f, p_target[i] - d);
            residual[i] = diff;
            sum += diff;
        }

        if (sum <= 1e-12f) {
            // Degenerate case fallback: sample directly from target
            return sampleDirect(p_target);
        }

        float r = dist_(rng_) * sum;
        float cumulative = 0.0f;
        for (size_t i = 0; i < residual.size(); ++i) {
            cumulative += residual[i];
            if (r <= cumulative) {
                return static_cast<int32_t>(i);
            }
        }
        return static_cast<int32_t>(residual.size() - 1);
    }

    int32_t sampleDirect(const std::vector<float>& probs) {
        float r = dist_(rng_);
        float cumulative = 0.0f;
        for (size_t i = 0; i < probs.size(); ++i) {
            cumulative += probs[i];
            if (r <= cumulative) {
                return static_cast<int32_t>(i);
            }
        }
        return static_cast<int32_t>(probs.size() - 1);
    }

    size_t vocab_size_;
    size_t draft_k_;
    std::mt19937 rng_;
    std::uniform_real_distribution<float> dist_;
};

} // namespace speculative
} // namespace leo

// ============================================================================
// C API Export for Python ctypes
// ============================================================================
extern "C" {

LEO_SPEC_EXPORT void* leo_speculative_create(size_t vocab_size, size_t draft_k, uint32_t seed) {
    return new leo::speculative::SpeculativeEngine(vocab_size, draft_k, seed);
}

LEO_SPEC_EXPORT void leo_speculative_pin_pcores() {
    leo::speculative::CoreAffinityManager::pinToPCores();
}

LEO_SPEC_EXPORT void leo_speculative_pin_ecores() {
    leo::speculative::CoreAffinityManager::pinToECores();
}

LEO_SPEC_EXPORT int leo_speculative_verify_step(
    void* handle,
    const int32_t* draft_tokens,
    const float* draft_probs_flat,
    const float* target_probs_flat,
    size_t k_len,
    size_t vocab_size,
    int32_t* out_accepted_tokens,
    size_t* out_accepted_count,
    int32_t* out_correction_token)
{
    if (!handle || !draft_tokens || !draft_probs_flat || !target_probs_flat) return -1;
    auto* engine = static_cast<leo::speculative::SpeculativeEngine*>(handle);

    leo::speculative::SpeculativeDraft draft;
    draft.k_length = k_len;
    draft.draft_tokens.assign(draft_tokens, draft_tokens + k_len);

    std::vector<std::vector<float>> target_probs_batch(k_len + 1, std::vector<float>(vocab_size));
    draft.draft_probs.resize(k_len, std::vector<float>(vocab_size));

    for (size_t step = 0; step < k_len; ++step) {
        std::copy(draft_probs_flat + step * vocab_size, draft_probs_flat + (step + 1) * vocab_size, draft.draft_probs[step].begin());
        std::copy(target_probs_flat + step * vocab_size, target_probs_flat + (step + 1) * vocab_size, target_probs_batch[step].begin());
    }
    std::copy(target_probs_flat + k_len * vocab_size, target_probs_flat + (k_len + 1) * vocab_size, target_probs_batch[k_len].begin());

    auto result = engine->verifyAndSample(draft, target_probs_batch);

    *out_accepted_count = result.accepted_count;
    for (size_t i = 0; i < result.accepted_tokens.size(); ++i) {
        out_accepted_tokens[i] = result.accepted_tokens[i];
    }
    *out_correction_token = result.correction_token;

    return 0;
}

LEO_SPEC_EXPORT void leo_speculative_free(void* handle) {
    if (handle) {
        delete static_cast<leo::speculative::SpeculativeEngine*>(handle);
    }
}

}

#endif // LEO_SPECULATIVE_ENGINE_HPP
