apiVersion: v1
kind: Service
metadata:
  name: hyper-api-service
spec:
  selector:
    app: hyper-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hyper-redis-master
spec:
  selector:
    app: hyper-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
