"""
hyper_cco/contract_compiler.py
==============================
Mechanism 4: Contract Compiler.
Converts application-declared requirements into an executable computation plan.

Optimizes for the CHEAPEST VALID PLAN, not the fastest invalid plan.
Selects among:
  - Exact execution
  - Exact reuse
  - Cached result
  - Sparse execution
  - Low-rank execution
  - Quantized execution
  - Reduced-resolution execution
  - Prediction
  - Residual correction
  - CPU execution
  - Intel iGPU execution
  - Hybrid CPU+iGPU execution
  - Full exact fallback
"""

from __future__ import annotations
import json
from enum import Enum
from dataclasses import dataclass, field, asdict
from typing import Dict, Any, Optional, List, Tuple
import numpy as np

from .contract import ComputeContract, ExactnessClass, CorrectnessTaxonomy


class ExecutionStrategy(str, Enum):
    EXACT_EXECUTION = "EXACT_EXECUTION"
    EXACT_REUSE = "EXACT_REUSE"
    CACHED_RESULT = "CACHED_RESULT"
    SPARSE_EXECUTION = "SPARSE_EXECUTION"
    LOW_RANK_EXECUTION = "LOW_RANK_EXECUTION"
    QUANTIZED_EXECUTION = "QUANTIZED_EXECUTION"
    REDUCED_RESOLUTION = "REDUCED_RESOLUTION"
    PREDICTION = "PREDICTION"
    RESIDUAL_CORRECTION = "RESIDUAL_CORRECTION"
    FULL_EXACT_FALLBACK = "FULL_EXACT_FALLBACK"


class TargetHardware(str, Enum):
    CPU = "CPU"
    INTEL_IGPU = "INTEL_IGPU"
    HYBRID_CPU_IGPU = "HYBRID_CPU_IGPU"


@dataclass
class CompiledPlan:
    """An executable computation plan generated by the Contract Compiler."""
    contract_id: str
    strategy: ExecutionStrategy
    target_hardware: TargetHardware
    precision: str                      # 'FP32', 'FP16', 'INT8', 'MIXED'
    estimated_cost_score: float         # Lower is cheaper
    estimated_latency_ms: float
    estimated_error: float
    verification_frequency: int         # e.g., 1 (every call), 10 (every 10 calls)
    fallback_policy: str                # 'EXACT', 'PREVIOUS_GOOD', 'ABORT'
    is_valid: bool = True
    rationale: str = ""

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["strategy"] = self.strategy.value
        d["target_hardware"] = self.target_hardware.value
        return d


class ContractCompiler:
    """
    Contract Compiler: Analyzes workload properties and active contract constraints
    to synthesize the cheapest valid execution plan.
    """
    def __init__(self):
        self.compilation_cache: Dict[str, CompiledPlan] = {}

    def compile(
        self,
        contract: ComputeContract,
        workload_profile: Dict[str, Any]
    ) -> CompiledPlan:
        """
        Compiles the contract into the cheapest valid plan.
        workload_profile keys:
          - 'total_flops': estimated baseline operations
          - 'input_size_bytes': memory footprint
          - 'temporal_similarity': [0.0, 1.0]
          - 'estimated_sparsity': [0.0, 1.0]
          - 'estimated_rank_ratio': rank / min(M, N)
          - 'cache_hit_available': bool
          - 'igpu_available': bool
          - 'current_thermal_c': float
        """
        cid = contract.workload_id
        max_err = contract.max_absolute_error if contract.max_absolute_error is not None else 1e-4
        max_lat = contract.max_latency_ms if contract.max_latency_ms is not None else 50.0
        thermal_limit = contract.custom_invariants.get("thermal_limit_c", 85.0)
        current_temp = workload_profile.get("current_thermal_c", 55.0)

        # Candidate evaluations: generate potential valid plans
        candidates: List[CompiledPlan] = []

        # 1. Exact Reuse / Cache
        if contract.allow_reuse and workload_profile.get("cache_hit_available", False):
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.CACHED_RESULT,
                target_hardware=TargetHardware.CPU,
                precision="FP32",
                estimated_cost_score=0.01,
                estimated_latency_ms=0.1,
                estimated_error=0.0,
                verification_frequency=100,
                fallback_policy="EXACT",
                rationale="Identical inputs detected: zero-compute content cache reuse"
            ))

        # 2. Temporal State Delta
        temporal_sim = workload_profile.get("temporal_similarity", 0.0)
        if contract.allow_reuse and temporal_sim >= 0.90:
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.EXACT_REUSE,
                target_hardware=TargetHardware.CPU,
                precision="FP32",
                estimated_cost_score=0.15,
                estimated_latency_ms=max_lat * 0.20,
                estimated_error=0.0,
                verification_frequency=10,
                fallback_policy="EXACT",
                rationale="High temporal similarity: state delta update"
            ))

        # 3. Sparse Execution
        sparsity = workload_profile.get("estimated_sparsity", 0.0)
        if contract.allow_reduced_work and sparsity >= 0.80:
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.SPARSE_EXECUTION,
                target_hardware=TargetHardware.CPU,
                precision="FP32",
                estimated_cost_score=0.30,
                estimated_latency_ms=max_lat * 0.35,
                estimated_error=0.0,
                verification_frequency=5,
                fallback_policy="EXACT",
                rationale=f"High sparsity ({sparsity:.2f}): CSR sparse kernel execution"
            ))

        # 4. Low-Rank + Residual
        rank_ratio = workload_profile.get("estimated_rank_ratio", 1.0)
        if contract.allow_approximation and rank_ratio <= 0.30 and max_err >= 1e-3:
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.LOW_RANK_EXECUTION,
                target_hardware=TargetHardware.CPU,
                precision="MIXED",
                estimated_cost_score=0.40,
                estimated_latency_ms=max_lat * 0.45,
                estimated_error=max_err * 0.50,
                verification_frequency=5,
                fallback_policy="EXACT",
                rationale=f"Subspace low-rank structure ({rank_ratio:.2f}): randomized SVD + residual"
            ))

        # 5. Quantized Execution
        if contract.allow_approximation and max_err >= 1e-2 and contract.output_dtype != "float64":
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.QUANTIZED_EXECUTION,
                target_hardware=TargetHardware.CPU,
                precision="INT8",
                estimated_cost_score=0.50,
                estimated_latency_ms=max_lat * 0.50,
                estimated_error=max_err * 0.70,
                verification_frequency=5,
                fallback_policy="EXACT",
                rationale="Error tolerance permits INT8 SIMD vectorization"
            ))

        # 6. Intel UHD iGPU Offload
        total_flops = workload_profile.get("total_flops", 1e6)
        igpu_avail = workload_profile.get("igpu_available", True)
        if igpu_avail and total_flops >= 1e8 and current_temp < thermal_limit:
            candidates.append(CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.EXACT_EXECUTION,
                target_hardware=TargetHardware.INTEL_IGPU,
                precision="FP32",
                estimated_cost_score=0.60,
                estimated_latency_ms=max_lat * 0.60,
                estimated_error=0.0,
                verification_frequency=20,
                fallback_policy="EXACT",
                rationale="Large parallel kernel exceeding 1e8 FLOPs: Intel UHD OpenCL offload"
            ))

        # 7. Baseline Exact CPU Execution (Always available baseline)
        candidates.append(CompiledPlan(
            contract_id=cid,
            strategy=ExecutionStrategy.EXACT_EXECUTION,
            target_hardware=TargetHardware.CPU,
            precision="FP32",
            estimated_cost_score=1.00,
            estimated_latency_ms=max_lat * 0.90,
            estimated_error=0.0,
            verification_frequency=1,
            fallback_policy="EXACT",
            rationale="Deterministic standard AVX2 CPU execution"
        ))

        # Filter candidates strictly by contract bounds
        valid_candidates = [
            c for c in candidates
            if c.estimated_error <= max_err and c.estimated_latency_ms <= max_lat
        ]

        if not valid_candidates:
            # If no candidate satisfies latency and error, fallback to full exact
            fallback = CompiledPlan(
                contract_id=cid,
                strategy=ExecutionStrategy.FULL_EXACT_FALLBACK,
                target_hardware=TargetHardware.CPU,
                precision="FP32",
                estimated_cost_score=2.00,
                estimated_latency_ms=max_lat,
                estimated_error=0.0,
                verification_frequency=1,
                fallback_policy="EXACT",
                is_valid=True,
                rationale="No optimized candidate satisfied constraints; full exact fallback"
            )
            return fallback

        # Sort valid candidates by estimated cost (ascending) to select CHEAPEST valid plan
        valid_candidates.sort(key=lambda c: c.estimated_cost_score)
        cheapest_plan = valid_candidates[0]
        self.compilation_cache[cid] = cheapest_plan
        return cheapest_plan
