import logging
from backend.core.database import SessionLocal, UsageLog
from sqlalchemy import func

logger = logging.getLogger(__name__)

class CostMonitor:
    """
    Tracks and calculates cost savings generated by the HYPER 12-layer stack.
    Estimates GPU cost avoided based on bypass hits.
    """
    # Industry standard estimates (cost per 1k tokens)
    MODEL_COST_ESTIMATE = 0.01 
    BYPASS_COST_ESTIMATE = 0.0001

    def calculate_savings(self, workspace_id: str) -> dict:
        db = SessionLocal()
        try:
            logs = db.query(UsageLog).filter(UsageLog.workspace_id == workspace_id).all()
            
            total_reqs = len(logs)
            full_inference_count = sum(1 for log in logs if log.inference_used)
            avoided_count = total_reqs - full_inference_count
            
            # Simplified savings calculation (dollars)
            estimated_savings = (avoided_count * self.MODEL_COST_ESTIMATE) - (total_reqs * self.BYPASS_COST_ESTIMATE)
            
            avoidance_ratio = (avoided_count / total_reqs) if total_reqs > 0 else 0
            
            return {
                "total_requests": total_reqs,
                "inference_avoided": avoided_count,
                "avoidance_ratio": round(avoidance_ratio, 4),
                "estimated_gpu_cost_saved": round(max(0, estimated_savings), 2)
            }
        except Exception as e:
            logger.error(f"cost_calculation_failed: {e}")
            return {}
        finally:
            db.close()

global_cost_monitor = CostMonitor()
