"""
hyper_x/independent_verifier.py
=============================================================================
HYPER-X: Decoupled Independent Verifier & Parity Metric Calculator
=============================================================================
Computes mathematical, perceptual, and performance metrics from raw recorded
experimental measurements with ZERO hardcoded scores or self-declared defaults.

Computes 3 Separate Metrics:
  Metric A: Reference-Relative Performance (P_ref, Uncapped)
  Metric B: Contract Attainment (PASS / FAIL)
  Metric C: Application Parity Percentage
"""

import numpy as np
from typing import Dict, Any, Tuple, Optional
from dataclasses import dataclass

@dataclass
class VerificationResult:
    metric_a_relative_performance_pct: float     # Uncapped ratio: T_ref / T_hyper * 100 or Throughput_hyper / Throughput_ref * 100
    metric_b_contract_attainment: bool           # PASS (True) or FAIL (False)
    metric_c_application_parity_pct: float       # min(100.0, P_ref) if contract PASS else 0.0
    work_elimination_ratio: float                # 1 - (Actual_Work / Reference_Work)
    relative_numerical_error: float              # ||Y_hyper - Y_ref||_F / ||Y_ref||_F
    perceptual_ssim: Optional[float]             # SSIM for vision/graphics
    perceptual_psnr_db: Optional[float]          # PSNR in dB for vision/graphics
    raw_reference_latency_ms: float
    raw_hyper_latency_ms: float
    raw_reference_throughput: float
    raw_hyper_throughput: float
    contract_tolerance_epsilon: float
    exactness_classification: str                # EXACT, NUMERICALLY_BOUNDED, PERCEPTUAL, REDUCED_WORK
    failure_reasons: list

class IndependentVerifier:
    """Decoupled verification and scorecard calculation engine."""

    @staticmethod
    def verify_matrix_workload(
        Y_ref: np.ndarray,
        Y_hyper: np.ndarray,
        T_ref_ms: float,
        T_hyper_ms: float,
        tolerance_epsilon: float = 0.01,
        latency_slo_ms: float = 150.0,
        nominal_reference_flops: float = 0.0,
        actual_hyper_flops: float = 0.0,
        exactness_class: str = "NUMERICALLY_BOUNDED"
    ) -> VerificationResult:
        """Verifies dense/sparse matrix workloads against reference BLAS output."""
        failures = []

        # 1. Exact Frobenius Numerical Error
        ref_norm = float(np.linalg.norm(Y_ref) + 1e-8)
        diff_norm = float(np.linalg.norm(Y_ref - Y_hyper))
        rel_error = diff_norm / ref_norm

        if rel_error > tolerance_epsilon:
            failures.append(f"Relative error {rel_error:.2e} exceeded tolerance {tolerance_epsilon:.2e}")

        # 2. Latency SLO Check
        if T_hyper_ms > latency_slo_ms:
            failures.append(f"HYPER latency {T_hyper_ms:.2f}ms exceeded SLO {latency_slo_ms:.2f}ms")

        # 3. Metric A: Reference-Relative Performance (Uncapped)
        p_ref = (T_ref_ms / max(1e-6, T_hyper_ms)) * 100.0

        # 4. Metric B: Contract Attainment
        contract_pass = (len(failures) == 0)

        # 5. Metric C: Application Parity (Capped at 100% only if Contract PASS)
        app_parity = min(100.0, (latency_slo_ms / max(1e-6, T_hyper_ms)) * 100.0) if contract_pass else 0.0

        # 6. Work Elimination Ratio
        wer = 1.0 - (actual_hyper_flops / max(1.0, nominal_reference_flops)) if nominal_reference_flops > 0 else 0.0

        return VerificationResult(
            metric_a_relative_performance_pct=round(p_ref, 2),
            metric_b_contract_attainment=contract_pass,
            metric_c_application_parity_pct=round(app_parity, 1),
            work_elimination_ratio=round(max(0.0, wer), 4),
            relative_numerical_error=round(rel_error, 8),
            perceptual_ssim=None,
            perceptual_psnr_db=None,
            raw_reference_latency_ms=round(T_ref_ms, 3),
            raw_hyper_latency_ms=round(T_hyper_ms, 3),
            raw_reference_throughput=round(1000.0 / max(1e-6, T_ref_ms), 2),
            raw_hyper_throughput=round(1000.0 / max(1e-6, T_hyper_ms), 2),
            contract_tolerance_epsilon=tolerance_epsilon,
            exactness_classification=exactness_class,
            failure_reasons=failures
        )

    @staticmethod
    def verify_language_workload(
        ref_tokens_per_sec: float,
        hyper_tokens_per_sec: float,
        target_tokens_per_sec: float,
        tokens_generated: int,
        ttft_ms: float,
        reference_params: int,
        hyper_params: int,
        exactness_class: str = "REDUCED_WORK"
    ) -> VerificationResult:
        """Verifies autoregressive neural decoding against reference baseline and target standard."""
        failures = []

        if tokens_generated < 1:
            failures.append("Zero tokens generated by engine.")

        # Metric A: Speedup vs Reference LLM
        p_ref = (hyper_tokens_per_sec / max(1e-6, ref_tokens_per_sec)) * 100.0

        # Metric B: Contract Attainment (Exceeds interactive human reading / target standard)
        contract_pass = (hyper_tokens_per_sec >= target_tokens_per_sec) and (len(failures) == 0)

        # Metric C: Application Parity
        app_parity = min(100.0, (hyper_tokens_per_sec / max(1e-6, target_tokens_per_sec)) * 100.0) if contract_pass else 0.0

        # WER: Parameter/computation reduction ratio
        wer = 1.0 - (hyper_params / max(1.0, reference_params))

        return VerificationResult(
            metric_a_relative_performance_pct=round(p_ref, 2),
            metric_b_contract_attainment=contract_pass,
            metric_c_application_parity_pct=round(app_parity, 1),
            work_elimination_ratio=round(max(0.0, wer), 4),
            relative_numerical_error=0.0,
            perceptual_ssim=None,
            perceptual_psnr_db=None,
            raw_reference_latency_ms=round(1000.0 / max(1e-6, ref_tokens_per_sec), 3),
            raw_hyper_latency_ms=round(1000.0 / max(1e-6, hyper_tokens_per_sec), 3),
            raw_reference_throughput=round(ref_tokens_per_sec, 2),
            raw_hyper_throughput=round(hyper_tokens_per_sec, 2),
            contract_tolerance_epsilon=0.0,
            exactness_classification=exactness_class,
            failure_reasons=failures
        )

    @staticmethod
    def verify_graphics_workload(
        frame_ref_gt: np.ndarray,
        frame_hyper: np.ndarray,
        target_fps: float,
        achieved_fps: float,
        samples_ref: int = 100,
        samples_hyper: int = 4,
        min_ssim: float = 0.92,
        min_psnr: float = 28.0,
        exactness_class: str = "PERCEPTUAL"
    ) -> VerificationResult:
        """Verifies reconstructed graphics frame against ground truth reference render."""
        failures = []

        # 1. Exact MSE & PSNR
        mse = float(np.mean((frame_ref_gt - frame_hyper) ** 2))
        max_val = 1.0
        psnr = float(20.0 * np.log10(max_val / np.sqrt(max(1e-10, mse))))

        # 2. Exact SSIM
        mu_x = float(np.mean(frame_ref_gt))
        mu_y = float(np.mean(frame_hyper))
        sigma_x = float(np.var(frame_ref_gt))
        sigma_y = float(np.var(frame_hyper))
        sigma_xy = float(np.mean((frame_ref_gt - mu_x) * (frame_hyper - mu_y)))
        c1 = (0.01 * max_val) ** 2
        c2 = (0.03 * max_val) ** 2
        ssim = float(((2 * mu_x * mu_y + c1) * (2 * sigma_xy + c2)) / ((mu_x**2 + mu_y**2 + c1) * (sigma_x + sigma_y + c2)))

        if ssim < min_ssim:
            failures.append(f"SSIM {ssim:.4f} below threshold {min_ssim:.4f}")
        if psnr < min_psnr:
            failures.append(f"PSNR {psnr:.2f}dB below threshold {min_psnr:.2f}dB")
        if achieved_fps < target_fps:
            failures.append(f"FPS {achieved_fps:.1f} below target {target_fps:.1f}")

        # Metric A: Performance vs 60 FPS target
        p_ref = (achieved_fps / max(1e-6, target_fps)) * 100.0

        # Metric B: Contract Attainment
        contract_pass = (len(failures) == 0)

        # Metric C: Application Parity
        app_parity = min(100.0, p_ref) if contract_pass else 0.0

        # WER: Sample reduction ratio
        wer = 1.0 - (samples_hyper / max(1.0, samples_ref))

        return VerificationResult(
            metric_a_relative_performance_pct=round(p_ref, 2),
            metric_b_contract_attainment=contract_pass,
            metric_c_application_parity_pct=round(app_parity, 1),
            work_elimination_ratio=round(max(0.0, wer), 4),
            relative_numerical_error=round(mse, 8),
            perceptual_ssim=round(ssim, 4),
            perceptual_psnr_db=round(psnr, 2),
            raw_reference_latency_ms=round(1000.0 / target_fps, 3),
            raw_hyper_latency_ms=round(1000.0 / max(1e-6, achieved_fps), 3),
            raw_reference_throughput=round(target_fps, 2),
            raw_hyper_throughput=round(achieved_fps, 2),
            contract_tolerance_epsilon=min_ssim,
            exactness_classification=exactness_class,
            failure_reasons=failures
        )

    @staticmethod
    def verify_simulation_workload(
        field_ref_dense: np.ndarray,
        field_hyper: np.ndarray,
        T_ref_dense_ms: float,
        T_hyper_ms: float,
        tolerance_epsilon: float = 0.05,
        exactness_class: str = "REDUCED_WORK"
    ) -> VerificationResult:
        """Verifies 2D scientific stencil simulation against dense stencil reference."""
        failures = []

        ref_norm = float(np.linalg.norm(field_ref_dense) + 1e-8)
        diff_norm = float(np.linalg.norm(field_ref_dense - field_hyper))
        rel_error = diff_norm / ref_norm

        if rel_error > tolerance_epsilon:
            failures.append(f"Relative error {rel_error:.2e} exceeded tolerance {tolerance_epsilon:.2e}")

        # Metric A: Speedup vs Dense Baseline
        p_ref = (T_ref_dense_ms / max(1e-6, T_hyper_ms)) * 100.0

        # Metric B: Contract Attainment
        contract_pass = (rel_error <= tolerance_epsilon) and (T_hyper_ms <= T_ref_dense_ms)

        # Metric C: Application Parity
        app_parity = min(100.0, p_ref) if contract_pass else 0.0

        # WER: Latency reduction ratio
        wer = 1.0 - (T_hyper_ms / max(1e-6, T_ref_dense_ms))

        return VerificationResult(
            metric_a_relative_performance_pct=round(p_ref, 2),
            metric_b_contract_attainment=contract_pass,
            metric_c_application_parity_pct=round(app_parity, 1),
            work_elimination_ratio=round(max(0.0, wer), 4),
            relative_numerical_error=round(rel_error, 8),
            perceptual_ssim=None,
            perceptual_psnr_db=None,
            raw_reference_latency_ms=round(T_ref_ms_ms:=T_ref_dense_ms, 3),
            raw_hyper_latency_ms=round(T_hyper_ms, 3),
            raw_reference_throughput=round(1000.0 / max(1e-6, T_ref_dense_ms), 2),
            raw_hyper_throughput=round(1000.0 / max(1e-6, T_hyper_ms), 2),
            contract_tolerance_epsilon=tolerance_epsilon,
            exactness_classification=exactness_class,
            failure_reasons=failures
        )
