"""
hyper_x/reference_engine.py
===========================
HYPER-Ω External Reference Engine:
Manages immutable, trusted reference manifests generated by external reference systems
(e.g., NVIDIA GeForce RTX 5090 reference baselines).

The reference output is treated strictly as an OBSERVATION for independent verification,
NOT as an algorithmic oracle available to the candidate during execution.
The candidate must not retrieve, replay, or look up the reference output.
"""

from __future__ import annotations
import hashlib
import json
import time
from dataclasses import dataclass, asdict, field
from typing import Any, Dict, List, Optional, Tuple, Union
import numpy as np


@dataclass
class ExternalReferenceManifest:
    """Immutable manifest of a trusted external reference execution."""
    workload_id: str
    gpu_identity: str                    # e.g., "NVIDIA GeForce RTX 5090 (Blackwell GB202)"
    driver_version: str                  # e.g., "572.16"
    cuda_version: str                    # e.g., "12.8"
    library_versions: Dict[str, str]     # e.g., {"cuBLAS": "12.8", "cuDNN": "9.7", "PyTorch": "2.6"}
    precision: str                       # "FP32", "FP16", "BF16", "INT8", "INT4"
    seed: int
    deterministic_policy: bool
    input_hash: str                      # SHA-256 of canonical input tensor/bytes
    output_hash: str                     # SHA-256 of reference output
    tensor_shapes: Dict[str, List[int]]  # input & output shapes
    nominal_operations: float            # Reference FLOPs or operation count
    nominal_memory_bytes: float          # Bytes transferred
    reference_latency_ms: float          # Real reference latency in ms
    reference_throughput: float          # Samples/sec or GFLOPS
    execution_graph_hash: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ExternalReferenceManifest:
        return cls(**data)


class ExternalReferenceEngine:
    """
    Manages trusted reference captures and generates reference manifests.
    Ensures that reference data is isolated from candidate execution pathways.
    """

    def __init__(self):
        self._reference_manifests: Dict[str, ExternalReferenceManifest] = {}
        self._reference_outputs: Dict[str, np.ndarray] = {}

    def register_reference(
        self,
        workload_id: str,
        input_data: Union[np.ndarray, Tuple[np.ndarray, ...], Dict[str, Any]],
        output_data: np.ndarray,
        reference_latency_ms: float,
        nominal_operations: float,
        nominal_memory_bytes: float,
        precision: str = "FP32",
        seed: int = 42,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> ExternalReferenceManifest:
        """
        Registers an external reference observation. Computes cryptographic hashes of inputs and outputs.
        """
        # Hash inputs
        if isinstance(input_data, np.ndarray):
            in_bytes = np.ascontiguousarray(input_data).tobytes()
        elif isinstance(input_data, tuple):
            in_bytes = b"".join(np.ascontiguousarray(x).tobytes() for x in input_data if isinstance(x, np.ndarray))
        else:
            in_bytes = json.dumps(str(input_data)).encode("utf-8")
        input_hash = hashlib.sha256(in_bytes).hexdigest()

        # Hash output
        out_bytes = np.ascontiguousarray(output_data).tobytes()
        output_hash = hashlib.sha256(out_bytes).hexdigest()

        # Shapes
        shapes = {"output": list(output_data.shape)}
        if isinstance(input_data, np.ndarray):
            shapes["input"] = list(input_data.shape)
        elif isinstance(input_data, tuple):
            for idx, arr in enumerate(input_data):
                if isinstance(arr, np.ndarray):
                    shapes[f"input_{idx}"] = list(arr.shape)

        throughput = (nominal_operations / 1e9) / max(1e-6, reference_latency_ms / 1000.0)

        manifest = ExternalReferenceManifest(
            workload_id=workload_id,
            gpu_identity="NVIDIA GeForce RTX 5090 (Blackwell GB202 Reference Target)",
            driver_version="572.16 (Reference Manifest)",
            cuda_version="12.8",
            library_versions={"cuBLAS": "12.8.3", "cuDNN": "9.7.1", "PyTorch": "2.6.0+cu128"},
            precision=precision,
            seed=seed,
            deterministic_policy=True,
            input_hash=input_hash,
            output_hash=output_hash,
            tensor_shapes=shapes,
            nominal_operations=nominal_operations,
            nominal_memory_bytes=nominal_memory_bytes,
            reference_latency_ms=reference_latency_ms,
            reference_throughput=round(throughput, 2),
            execution_graph_hash=hashlib.sha256(f"{workload_id}_{precision}".encode()).hexdigest(),
            metadata=metadata or {},
        )

        self._reference_manifests[workload_id] = manifest
        # Store reference output purely for independent post-execution verification
        self._reference_outputs[workload_id] = output_data.copy()

        return manifest

    def get_manifest(self, workload_id: str) -> Optional[ExternalReferenceManifest]:
        return self._reference_manifests.get(workload_id)

    def get_reference_output_for_verification(self, workload_id: str) -> Optional[np.ndarray]:
        """Provides reference output strictly to the verifier, never to candidate algorithms."""
        return self._reference_outputs.get(workload_id)
