/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppBenchmarksRouteImport } from './routes/_authenticated.app.benchmarks'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated.app.chat'
import { Route as AuthenticatedAppEmbeddingsRouteImport } from './routes/_authenticated.app.embeddings'
import { Route as AuthenticatedAppHardwareBoostRouteImport } from './routes/_authenticated.app.hardware-boost'
import { Route as AuthenticatedAppKnowledgeGraphRouteImport } from './routes/_authenticated.app.knowledge-graph'
import { Route as AuthenticatedAppMemoryRouteImport } from './routes/_authenticated.app.memory'
import { Route as AuthenticatedAppOrchestrateRouteImport } from './routes/_authenticated.app.orchestrate'
import { Route as AuthenticatedAppSecurityRouteImport } from './routes/_authenticated.app.security'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as ApiV1LeoMetricsRouteImport } from './routes/api/v1/leo/metrics'
import { Route as ApiV1LeoMetricsStreamRouteImport } from './routes/api/v1/leo/metrics.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBenchmarksRoute =
  AuthenticatedAppBenchmarksRouteImport.update({
    id: '/benchmarks',
    path: '/benchmarks',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEmbeddingsRoute =
  AuthenticatedAppEmbeddingsRouteImport.update({
    id: '/embeddings',
    path: '/embeddings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHardwareBoostRoute =
  AuthenticatedAppHardwareBoostRouteImport.update({
    id: '/hardware-boost',
    path: '/hardware-boost',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppKnowledgeGraphRoute =
  AuthenticatedAppKnowledgeGraphRouteImport.update({
    id: '/knowledge-graph',
    path: '/knowledge-graph',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMemoryRoute = AuthenticatedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrchestrateRoute =
  AuthenticatedAppOrchestrateRouteImport.update({
    id: '/orchestrate',
    path: '/orchestrate',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSecurityRoute =
  AuthenticatedAppSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiV1LeoMetricsRoute = ApiV1LeoMetricsRouteImport.update({
  id: '/api/v1/leo/metrics',
  path: '/api/v1/leo/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeoMetricsStreamRoute = ApiV1LeoMetricsStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiV1LeoMetricsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/embeddings': typeof AuthenticatedAppEmbeddingsRoute
  '/app/hardware-boost': typeof AuthenticatedAppHardwareBoostRoute
  '/app/knowledge-graph': typeof AuthenticatedAppKnowledgeGraphRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/orchestrate': typeof AuthenticatedAppOrchestrateRoute
  '/app/security': typeof AuthenticatedAppSecurityRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/v1/leo/metrics': typeof ApiV1LeoMetricsRouteWithChildren
  '/api/v1/leo/metrics/stream': typeof ApiV1LeoMetricsStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/signup': typeof SignupRoute
  '/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/embeddings': typeof AuthenticatedAppEmbeddingsRoute
  '/app/hardware-boost': typeof AuthenticatedAppHardwareBoostRoute
  '/app/knowledge-graph': typeof AuthenticatedAppKnowledgeGraphRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/orchestrate': typeof AuthenticatedAppOrchestrateRoute
  '/app/security': typeof AuthenticatedAppSecurityRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/v1/leo/metrics': typeof ApiV1LeoMetricsRouteWithChildren
  '/api/v1/leo/metrics/stream': typeof ApiV1LeoMetricsStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/benchmarks': typeof AuthenticatedAppBenchmarksRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/embeddings': typeof AuthenticatedAppEmbeddingsRoute
  '/_authenticated/app/hardware-boost': typeof AuthenticatedAppHardwareBoostRoute
  '/_authenticated/app/knowledge-graph': typeof AuthenticatedAppKnowledgeGraphRoute
  '/_authenticated/app/memory': typeof AuthenticatedAppMemoryRoute
  '/_authenticated/app/orchestrate': typeof AuthenticatedAppOrchestrateRoute
  '/_authenticated/app/security': typeof AuthenticatedAppSecurityRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/v1/leo/metrics': typeof ApiV1LeoMetricsRouteWithChildren
  '/api/v1/leo/metrics/stream': typeof ApiV1LeoMetricsStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/benchmarks'
    | '/docs'
    | '/features'
    | '/login'
    | '/platform'
    | '/signup'
    | '/app'
    | '/app/benchmarks'
    | '/app/chat'
    | '/app/embeddings'
    | '/app/hardware-boost'
    | '/app/knowledge-graph'
    | '/app/memory'
    | '/app/orchestrate'
    | '/app/security'
    | '/app/settings'
    | '/app/'
    | '/api/v1/leo/metrics'
    | '/api/v1/leo/metrics/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benchmarks'
    | '/docs'
    | '/features'
    | '/login'
    | '/platform'
    | '/signup'
    | '/app/benchmarks'
    | '/app/chat'
    | '/app/embeddings'
    | '/app/hardware-boost'
    | '/app/knowledge-graph'
    | '/app/memory'
    | '/app/orchestrate'
    | '/app/security'
    | '/app/settings'
    | '/app'
    | '/api/v1/leo/metrics'
    | '/api/v1/leo/metrics/stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/benchmarks'
    | '/docs'
    | '/features'
    | '/login'
    | '/platform'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/app/benchmarks'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/embeddings'
    | '/_authenticated/app/hardware-boost'
    | '/_authenticated/app/knowledge-graph'
    | '/_authenticated/app/memory'
    | '/_authenticated/app/orchestrate'
    | '/_authenticated/app/security'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/api/v1/leo/metrics'
    | '/api/v1/leo/metrics/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BenchmarksRoute: typeof BenchmarksRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRoute
  SignupRoute: typeof SignupRoute
  ApiV1LeoMetricsRoute: typeof ApiV1LeoMetricsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benchmarks': {
      id: '/_authenticated/app/benchmarks'
      path: '/benchmarks'
      fullPath: '/app/benchmarks'
      preLoaderRoute: typeof AuthenticatedAppBenchmarksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/embeddings': {
      id: '/_authenticated/app/embeddings'
      path: '/embeddings'
      fullPath: '/app/embeddings'
      preLoaderRoute: typeof AuthenticatedAppEmbeddingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hardware-boost': {
      id: '/_authenticated/app/hardware-boost'
      path: '/hardware-boost'
      fullPath: '/app/hardware-boost'
      preLoaderRoute: typeof AuthenticatedAppHardwareBoostRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/knowledge-graph': {
      id: '/_authenticated/app/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/app/knowledge-graph'
      preLoaderRoute: typeof AuthenticatedAppKnowledgeGraphRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory': {
      id: '/_authenticated/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AuthenticatedAppMemoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orchestrate': {
      id: '/_authenticated/app/orchestrate'
      path: '/orchestrate'
      fullPath: '/app/orchestrate'
      preLoaderRoute: typeof AuthenticatedAppOrchestrateRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/security': {
      id: '/_authenticated/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AuthenticatedAppSecurityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/v1/leo/metrics': {
      id: '/api/v1/leo/metrics'
      path: '/api/v1/leo/metrics'
      fullPath: '/api/v1/leo/metrics'
      preLoaderRoute: typeof ApiV1LeoMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leo/metrics/stream': {
      id: '/api/v1/leo/metrics/stream'
      path: '/stream'
      fullPath: '/api/v1/leo/metrics/stream'
      preLoaderRoute: typeof ApiV1LeoMetricsStreamRouteImport
      parentRoute: typeof ApiV1LeoMetricsRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBenchmarksRoute: typeof AuthenticatedAppBenchmarksRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppEmbeddingsRoute: typeof AuthenticatedAppEmbeddingsRoute
  AuthenticatedAppHardwareBoostRoute: typeof AuthenticatedAppHardwareBoostRoute
  AuthenticatedAppKnowledgeGraphRoute: typeof AuthenticatedAppKnowledgeGraphRoute
  AuthenticatedAppMemoryRoute: typeof AuthenticatedAppMemoryRoute
  AuthenticatedAppOrchestrateRoute: typeof AuthenticatedAppOrchestrateRoute
  AuthenticatedAppSecurityRoute: typeof AuthenticatedAppSecurityRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBenchmarksRoute: AuthenticatedAppBenchmarksRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppEmbeddingsRoute: AuthenticatedAppEmbeddingsRoute,
  AuthenticatedAppHardwareBoostRoute: AuthenticatedAppHardwareBoostRoute,
  AuthenticatedAppKnowledgeGraphRoute: AuthenticatedAppKnowledgeGraphRoute,
  AuthenticatedAppMemoryRoute: AuthenticatedAppMemoryRoute,
  AuthenticatedAppOrchestrateRoute: AuthenticatedAppOrchestrateRoute,
  AuthenticatedAppSecurityRoute: AuthenticatedAppSecurityRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiV1LeoMetricsRouteChildren {
  ApiV1LeoMetricsStreamRoute: typeof ApiV1LeoMetricsStreamRoute
}

const ApiV1LeoMetricsRouteChildren: ApiV1LeoMetricsRouteChildren = {
  ApiV1LeoMetricsStreamRoute: ApiV1LeoMetricsStreamRoute,
}

const ApiV1LeoMetricsRouteWithChildren = ApiV1LeoMetricsRoute._addFileChildren(
  ApiV1LeoMetricsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BenchmarksRoute: BenchmarksRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRoute,
  SignupRoute: SignupRoute,
  ApiV1LeoMetricsRoute: ApiV1LeoMetricsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
