/**
 * Legal / Medical Preparation Layer (Compliance Guardian)
 *
 * Ensures that the system NEVER makes a final decision on sensitive topics.
 * It strictly outputs "Preparation Bundles" for human review.
 */

export interface ComplianceBundle {
  trace_id: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  content: any;
  disclaimers: string[];
  auditable_log: string;
}

export class ComplianceGuardian {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  public static wrapResponse(content: any, type: "LEGAL" | "MEDICAL"): ComplianceBundle {
    const traceId = `audit-${Date.now()}-${Math.floor(Math.random() * 1000)}`;

    const disclaimers = [
      "Generated by AI System - NOT A HUMAN EXPERT.",
      "This is a PREPARATION DOCUMENT, not a final decision.",
      "Human review and sign-off is MANDATORY.",
    ];

    if (type === "LEGAL") {
      disclaimers.push("NOT LEGAL ADVICE. Consult a qualified attorney.");
    } else if (type === "MEDICAL") {
      disclaimers.push("NOT MEDICAL ADVICE. Consult a physician immediately.");
    }

    console.log(`[ComplianceGuardian] Wrapping response ${traceId} with ${type} safeguards.`);

    return {
      trace_id: traceId,
      content: content,
      disclaimers: disclaimers,
      auditable_log: `Trace ${traceId}: Content generated at ${new Date().toISOString()} under strict non-decision protocols.`,
    };
  }
}
